# Generated by Django 5.1.4 on 2025-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heliostat',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='position_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='curvature_e',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='receiver',
            name='curvature_u',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='receiver',
            name='height',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='receiver',
            name='plane_e',
            field=models.FloatField(default=8.629666667),
        ),
        migrations.AddField(
            model_name='receiver',
            name='plane_u',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='position_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='resolution_e',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='receiver',
            name='resolution_u',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='receiver',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
