# Generated by Django 5.1.4 on 2025-01-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_receiver_curvature_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='curvature_u',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
