# Generated by Django 5.1.4 on 2025-01-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_alter_receiver_curvature_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='curvature_e',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='curvature_u',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
