# Generated by Django 5.1.4 on 2025-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_alter_receiver_curvature_e_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heliostat',
            name='rotation_x',
        ),
        migrations.RemoveField(
            model_name='heliostat',
            name='rotation_y',
        ),
        migrations.RemoveField(
            model_name='heliostat',
            name='rotation_z',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='height',
        ),
        migrations.AddField(
            model_name='heliostat',
            name='aimpoint_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='aimpoint_y',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='aimpoint_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lightsource',
            name='covariance',
            field=models.FloatField(default=4.3681e-06),
        ),
        migrations.AddField(
            model_name='lightsource',
            name='distribution_type',
            field=models.CharField(default='normal', max_length=300),
        ),
        migrations.AddField(
            model_name='lightsource',
            name='lightsource_type',
            field=models.CharField(default='sun', max_length=300),
        ),
        migrations.AddField(
            model_name='lightsource',
            name='mean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lightsource',
            name='number_of_rays',
            field=models.IntegerField(default=100),
        ),
    ]
