# Generated by Django 5.1.4 on 2025-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_remove_heliostat_rotation_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heliostat',
            name='kinematic_type',
            field=models.CharField(default='ideal', max_length=300),
        ),
        migrations.AddField(
            model_name='heliostat',
            name='number_of_facets',
            field=models.IntegerField(default=4),
        ),
    ]
