# Generated by Django 5.1.4 on 2025-01-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_heliostat_kinematic_type_heliostat_number_of_facets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='rotation',
            new_name='rotation_y',
        ),
    ]
